coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8090
query.max-memory=2GB
query.max-memory-per-node=1GB
query.max-total-memory-per-node=2GB
discovery.uri=http://trino:8090
node.environment=production
node.id=trino-coordinator-01
node.data-dir=/var/trino/data
