apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse-streamflow
    isDefault: true
    jsonData:
      host: clickhouse
      port: 8123
      protocol: http
      defaultDatabase: analytics
      username: streamflow
      dialTimeout: "10"
      queryTimeout: "60"
      tlsSkipVerify: true
    secureJsonData:
      password: streamflow123

  - name: Prometheus
    type: prometheus
    uid: prometheus-main
    url: http://prometheus:9090
    access: proxy
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: "2.47.0"

  - name: PostgreSQL
    type: postgres
    uid: postgres-main
    url: postgres:5432
    database: streamflow_source
    user: streamflow
    access: proxy
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1500
    secureJsonData:
      password: streamflow123
